// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
//  Created by Sam Deane on 23/07/2026.
//  Copyright © 2026 Elegant Chaos Limited. All rights reserved.
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

import Foundation

/// Generates GitHub workflow files and optional README headers for a repository.
public final class Generator {
  /// Repository-relative path for the generated Swift reusable workflow.
  static let swiftJobPath = ".github/workflows/ActionBuilderSwiftJob.yml"

  /// Repository-relative path for the generated Xcode reusable workflow.
  static let xcodeJobPath = ".github/workflows/ActionBuilderXcodeJob.yml"

  /// Name of the generating tool.
  let name: String
  /// Version string embedded in generated output.
  let version: String
  /// Documentation URL embedded in generated output.
  let link: String

  /// Creates a generator with metadata included in generated files.
  public init(name: String, version: String, link: String) {
    self.name = name
    self.version = version
    self.link = link
  }

  /// Generates the caller and reusable workflow files for a repository.
  public func workflowFiles(for repo: Repo) -> [GeneratedWorkflowFile] {
    [
      GeneratedWorkflowFile(
        relativePath: ".github/workflows/\(workflowFilename(for: repo)).yml",
        contents: workflow(for: repo)
      ),
      GeneratedWorkflowFile(
        relativePath: Self.swiftJobPath,
        contents: swiftJobWorkflow(for: repo)
      ),
      GeneratedWorkflowFile(
        relativePath: Self.xcodeJobPath,
        contents: xcodeJobWorkflow(for: repo)
      ),
    ]
  }

  /// Returns the concise caller workflow for the given repository.
  public func workflow(for repo: Repo) -> String {
    let compilers = repo.compilersToTest
    let platforms = repo.enabledPlatforms

    var source =
      """
      # --------------------------------------------------------------------------------
      # This workflow was automatically generated by \(name) \(version).
      # (see \(link) for more details)
      #
      # Job implementations:
      #   \(Self.swiftJobPath)
      #   \(Self.xcodeJobPath)
      # --------------------------------------------------------------------------------

      name: \(YAML.quoted(repo.workflow))

      on: [push, pull_request]

      jobs:
      """

    for platform in platforms {
      source.append(platform.yaml(repo: repo, compilers: compilers))
    }

    return source
  }

  /// Returns the standard header embedded in generated reusable workflows.
  func reusableWorkflowHeader() -> String {
    """
    # --------------------------------------------------------------------------------
    # This workflow was automatically generated by \(name) \(version).
    # (see \(link) for more details)
    # --------------------------------------------------------------------------------

    """ + "\n"
  }

  /// Returns a safe filename derived from the configured workflow name.
  func workflowFilename(for repo: Repo) -> String {
    let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-_. "))
    let filename =
      repo.workflow.unicodeScalars
      .map { allowed.contains($0) ? String($0) : "-" }
      .joined()
    return filename.isEmpty ? Repo.defaultWorkflow : filename
  }

  /// Generates text to use for a README.md header for the given repo.
  public func header(for repo: Repo) -> (String, String) {
    let platforms = repo.enabledPlatforms
    let compilers = repo.enabledCompilers

    var header = ""
    let headerDelimiter = "<!-- End of \(name) Header -->\n\n"
    if repo.header {
      let platformNames = platforms.map({ $0.name }).joined(separator: ", ")
      let platformIDs = platforms.map({ $0.name })
      let swiftBadges = compilers.map({ "![swift \($0.short) shield]" }).joined(separator: " ")
      let swiftShields = compilers.map({ "[swift \($0.short) shield]: \(ImageShield.imgShieldURL(for: repo, compiler: $0)) \"Swift \($0.short)\"" }).joined(
        separator: "\n")

      header += """
        <!-- Header Generated by \(name) \(version) -->
        <!-- See \(link) for more details. -->

        [![Test results][tests shield]][actions] [![Latest release][release shield]][releases] [\(swiftBadges)][swift] ![Platforms: \(platformNames)][platforms shield]

        [release shield]: \(ImageShield.imgShieldURL(for: repo, type: .release))
        [platforms shield]: \(ImageShield.imgShieldURL(for: repo, platforms: platformIDs)) "\(platformNames)"
        [tests shield]: \(GitHub.githubURL(for: repo, location: .badge("")))
        \(swiftShields)

        [swift]: https://swift.org
        [releases]: \(GitHub.githubURL(for: repo, location: .releases))
        [actions]: \(GitHub.githubURL(for: repo, location: .actions))

        \(headerDelimiter)
        """
    }

    return (header, headerDelimiter)
  }
}
