import ChaosTesting
import Foundation
import Matchable
import Testing

@testable import ActionBuilderCore

@Test
func testParsingPackageOldPlatform() async throws {
  // test extracting Swift version from a package which has an older tools version
  // than we currently support.
  let examplePackage = Bundle.module.url(forResource: "Example-old", withExtension: "package")!
  let repo = try await Repo(forPackage: examplePackage)
  #expect(Set(repo.enabledCompilers.map { $0.id }) == Set([.earliestRelease, .latestRelease]))
}

@Test
func testParsingPackageMacPlatform() async throws {
  // test extracting the Swift version and platforms from a package with macOS support
  let examplePackage = Bundle.module.url(forResource: "Example-mac", withExtension: "package")!
  let repo = try await Repo(forPackage: examplePackage)
  #expect(Set(repo.enabledCompilers.map { $0.id }) == Set([.swift510, .latestRelease]))
  #expect(repo.enabledPlatforms.map { $0.id } == [.macOS])
}

@Test
func testParsingPackageMultiPlatform() async throws {
  // test extracting the Swift version and platforms from a package with multiple platform support
  let examplePackage = Bundle.module.url(forResource: "Example-multi", withExtension: "package")!
  let repo = try await Repo(forPackage: examplePackage)
  #expect(repo.compilers == [.swift60, .swiftLatest])
  #expect(repo.platforms == [.iOS, .linux, .macOS, .tvOS])
}

@Test
func testParsingPackageConfigFile() async throws {
  let examplePackage = Bundle.module.url(forResource: "Example-config", withExtension: "package")!
  let repo = try await Repo(forPackage: examplePackage)
  #expect(repo.name == "ConfigTestPackage")
  #expect(repo.owner == "ConfigTestOwner")
  #expect(repo.compilers == [.swift60, .swiftNightly])
  #expect(repo.platforms == [.macOS, .linux])
  #expect(repo.testMode == .test)
  #expect(!repo.header)
  #expect(!repo.uploadLogs)
  #expect(!repo.postSlackNotification)
  #expect(!repo.firstlast)
}

@Test
func testParsingPackageFutureToolsVersion() async throws {
  // Future tools versions should collapse to latest known release via swiftLatest.
  let examplePackage = Bundle.module.url(forResource: "Example-future", withExtension: "package")!
  let repo = try await Repo(forPackage: examplePackage)
  #expect(repo.compilers == [.swiftLatest])
  #expect(Set(repo.enabledCompilers.map { $0.id }) == Set([.latestRelease]))
}

@Test
func testLegacyCompilerIDsMapToEarliestSupportedRelease() {
  // Legacy compiler IDs are accepted for compatibility but mapped to earliest supported.
  let repo = Repo(
    name: "testRepo", owner: "testOwner", platforms: [.macOS],
    compilers: [.swift57, .swift58, .swift59, .swiftLatest], firstlast: false)

  #expect(Set(repo.enabledCompilers.map { $0.id }) == Set([.earliestRelease, .latestRelease]))
}

@Test
func testYAMLmacOSSwift57() async throws {
  let expected = """
    # --------------------------------------------------------------------------------
    # This workflow was automatically generated by Test Generator 1.2.3 (456).
    # (see https://test.com for more details)
    # --------------------------------------------------------------------------------
    name: Tests
    on: [push, pull_request]
    jobs:
        macOS-swift510:
            name: macOS (Swift 5.10)
            runs-on: macos-14
            steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Make Logs Directory
              run: mkdir logs
            - name: Install xcbeautify
              run: |
                if command -v xcbeautify >/dev/null 2>&1
                then
                  echo "xcbeautify already installed."
                elif brew install xcbeautify > logs/install-xcbeautify.log 2>&1
                then
                  echo "xcbeautify installed."
                else
                  echo "::error::Failed to install xcbeautify."
                  cat logs/install-xcbeautify.log
                  exit 1
                fi
            - name: Select Swift
              uses: swift-actions/setup-swift@v3
              with:
                swift-version: "5.10"
            - name: Swift Version
              run: swift --version
            - name: Build (release)
              run: |
                LOG="logs/swift-build-release.log"
                if swift build --configuration release --quiet >"$LOG" 2>&1
                then
                  echo "Build (release) succeeded."
                else
                  echo "::error::Build (release) failed."
                  cat "$LOG" | xcbeautify --quiet --disable-logging --renderer github-actions || cat "$LOG"
                  echo "Build (release) failed."
                  exit 1
                fi
            - name: Test (release)
              run: |
                LOG="logs/swift-test-release.log"
                if swift test --configuration release >"$LOG" 2>&1
                then
                  echo "Test (release) succeeded."
                else
                  echo "::error::Test (release) failed."
                  cat "$LOG" | xcbeautify --quiet --disable-logging --renderer github-actions || cat "$LOG"
                  echo "Test (release) failed."
                  exit 1
                fi
            - name: Upload Logs
              uses: actions/upload-artifact@v7
              if: always()
              with:
                name: macOS-swift510-logs
                path: logs

    """

  let generator = Generator(
    name: "Test Generator", version: "1.2.3 (456)", link: "https://test.com")
  let repo = Repo(name: "testRepo", owner: "testOwner", platforms: [.macOS], compilers: [.swift510])

  let source = generator.workflow(for: repo)
  try source.assertMatches(expected)
}

@Test
func testYAMLiOSSwift57() throws {
  let expected = """
    # --------------------------------------------------------------------------------
    # This workflow was automatically generated by Test Generator 1.2.3 (456).
    # (see https://test.com for more details)
    # --------------------------------------------------------------------------------
    name: Tests
    on: [push, pull_request]
    jobs:
        xcode-swift510:
            name: iOS (Swift 5.10, Xcode matching Swift 5.10)
            runs-on: macos-14
            steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Make Logs Directory
              run: mkdir logs
            - name: Install xcbeautify
              run: |
                if command -v xcbeautify >/dev/null 2>&1
                then
                  echo "xcbeautify already installed."
                elif brew install xcbeautify > logs/install-xcbeautify.log 2>&1
                then
                  echo "xcbeautify installed."
                else
                  echo "::error::Failed to install xcbeautify."
                  cat logs/install-xcbeautify.log
                  exit 1
                fi
            - name: Resolve Xcode Version
              id: resolve-xcode
              run: |
                REQUESTED_SWIFT="5.10"
                ls -d /Applications/Xcode* > logs/xcode-versions.log
                FOUND_XCODE=""
                while read -r APP
                do
                  DEV_DIR="$APP/Contents/Developer"
                  SWIFT_VERSION=$(DEVELOPER_DIR="$DEV_DIR" xcrun swift --version 2>/dev/null | head -n 1 | sed -E 's/.*version ([0-9]+\\.[0-9]+).*/\\1/')
                  XCODE_VERSION=$(DEVELOPER_DIR="$DEV_DIR" xcodebuild -version 2>/dev/null | awk '/^Xcode / {print $2; exit}')
                  if [[ "$SWIFT_VERSION" == "$REQUESTED_SWIFT" ]]
                  then
                    FOUND_XCODE="$XCODE_VERSION"
                    break
                  fi
                done < <(ls -d /Applications/Xcode*.app | sort -Vr)

                if [[ "$FOUND_XCODE" == "" ]]
                then
                  echo "No installed Xcode matched Swift $REQUESTED_SWIFT."
                  echo "Detected toolchains:"
                  while read -r APP
                  do
                    DEV_DIR="$APP/Contents/Developer"
                    XCODE_VERSION=$(DEVELOPER_DIR="$DEV_DIR" xcodebuild -version 2>/dev/null | awk '/^Xcode / {print $2; exit}')
                    SWIFT_VERSION=$(DEVELOPER_DIR="$DEV_DIR" xcrun swift --version 2>/dev/null | head -n 1 | sed -E 's/.*version ([0-9]+\\.[0-9]+).*/\\1/')
                    echo "  Xcode $XCODE_VERSION -> Swift $SWIFT_VERSION"
                  done < <(ls -d /Applications/Xcode*.app | sort -Vr)
                  exit 1
                fi

                echo "version=$FOUND_XCODE" >> "$GITHUB_OUTPUT"
            - name: Select Xcode Version
              uses: maxim-lobanov/setup-xcode@v1
              with:
                xcode-version: ${{ steps.resolve-xcode.outputs.version }}
            - name: Xcode Version
              run: |
                xcodebuild -version
                swift --version
            - name: Prepare Destination Picker
              run: |
                cat > destination-picker.sh <<'EOF'
                extract_destination_field() {
                  local line="$1"
                  local field="$2"
                  printf '%s\\n' "$line" | sed -nE "s/.*${field}:[[:space:]]*([^,}]+).*/\\\\1/p" | xargs
                }
                load_best_destination() {
                  local destinations_log="$1"
                  local simulator_platform="$2"
                  local device_name_prefix="$3"
                  BEST_DESTINATION=$(
                    while IFS= read -r line
                    do
                      [[ "$line" == *"platform:${simulator_platform}"* ]] || continue
                      [[ "$line" == *"name:${device_name_prefix}"* ]] || continue
                      [[ "$line" != *"unavailable"* ]] || continue

                      id=$(extract_destination_field "$line" "id")
                      os=$(extract_destination_field "$line" "OS")
                      name=$(extract_destination_field "$line" "name")

                      [[ -n "$id" && -n "$os" ]] || continue

                      IFS=. read -r major minor patch <<< "$os"
                      printf "%d\\t%d\\t%d\\t%s\\t%s\\t%s\\n" "${major:-0}" "${minor:-0}" "${patch:-0}" "$os" "$id" "$name"
                    done < "$destinations_log" | sort -k1,1nr -k2,2nr -k3,3nr | head -n 1
                  )
                  DESTINATION_OS=$(echo "$BEST_DESTINATION" | awk -F"\\t" '{print $4}' | xargs)
                  DESTINATION_ID=$(echo "$BEST_DESTINATION" | awk -F"\\t" '{print $5}' | xargs)
                  DESTINATION_NAME=$(echo "$BEST_DESTINATION" | awk -F"\\t" '{print $6}' | xargs)
                  [[ "$DESTINATION_NAME" != "" && "$DESTINATION_OS" != "" ]]
                }
                pick_destination_if_available() {
                  local platform_id="$1"
                  local simulator_platform="$2"
                  local device_name_prefix="$3"
                  local destinations_log="logs/destinations-${platform_id}.log"

                  load_best_destination "$destinations_log" "$simulator_platform" "$device_name_prefix"
                }
                pick_destination() {
                  local platform_id="$1"
                  local simulator_platform="$2"
                  local device_name_prefix="$3"
                  local failure_message="$4"
                  local destinations_log="logs/destinations-${platform_id}.log"

                  if ! load_best_destination "$destinations_log" "$simulator_platform" "$device_name_prefix"
                  then
                    echo "::error::$failure_message"
                    cat "$destinations_log"
                    exit 1
                  fi
                }
                boot_destination() {
                  local platform_id="$1"
                  local platform_name="$2"
                  local boot_log="logs/boot-${platform_id}.log"

                  echo "Booting ${platform_name} simulator ${DESTINATION_NAME:-unknown} (OS ${DESTINATION_OS:-unknown}, id=${DESTINATION_ID:-unknown})."
                  xcrun simctl boot "$DESTINATION_ID" >"$boot_log" 2>&1 || true
                  if ! xcrun simctl bootstatus "$DESTINATION_ID" -b >>"$boot_log" 2>&1
                  then
                    echo "::error::Failed to boot ${platform_name} simulator ${DESTINATION_NAME:-unknown} (OS ${DESTINATION_OS:-unknown}, id=${DESTINATION_ID:-unknown})."
                    cat "$boot_log"
                    exit 1
                  fi
                }
                EOF
            - name: Detect Workspace & Scheme (iOS)
              run: |
                WORKSPACE="testRepo.xcworkspace"
                if [[ ! -e "$WORKSPACE" ]]
                then
                  WORKSPACE="."
                  GOTPACKAGE=$(xcodebuild -workspace . -list | (grep testRepo-Package || true))
                  if [[ $GOTPACKAGE != "" ]]
                  then
                    SCHEME="testRepo-Package"
                  else
                    SCHEME="testRepo"
                  fi
                else
                  SCHEME="testRepo-iOS"
                fi
                echo "export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
            - name: Test (iOS Release)
              run: |
                set -o pipefail
                source "setup.sh"
                source "destination-picker.sh"
                xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -showdestinations > logs/destinations-iOS.log
                if pick_destination_if_available "iOS" "iOS Simulator" "iPhone"
                then
                  echo "Using existing iOS simulator destination."
                else
                  echo "No available iOS simulator destination found. Downloading platform support."
                  xcodebuild -downloadPlatform iOS > logs/download-iOS.log
                  xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -showdestinations > logs/destinations-iOS.log
                  pick_destination "iOS" "iOS Simulator" "iPhone" "No available non-beta iPhone simulator destination found."
                fi
                echo "Selected iOS simulator: ${DESTINATION_NAME:-unknown} (OS ${DESTINATION_OS:-unknown}, id=${DESTINATION_ID:-unknown})."
                boot_destination "iOS" "iOS"
                echo "Testing workspace $WORKSPACE scheme $SCHEME on ${DESTINATION_NAME:-unknown} (iOS ${DESTINATION_OS:-unknown}, id=${DESTINATION_ID:-unknown})."
                xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "platform=iOS Simulator,OS=$DESTINATION_OS,name=$DESTINATION_NAME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcbeautify --quiet --disable-logging --renderer github-actions
            - name: Upload Logs
              uses: actions/upload-artifact@v7
              if: always()
              with:
                name: xcode-swift510-logs
                path: logs

    """

  let generator = Generator(
    name: "Test Generator", version: "1.2.3 (456)", link: "https://test.com")
  let repo = Repo(name: "testRepo", owner: "testOwner", platforms: [.iOS], compilers: [.swift510])

  let source = generator.workflow(for: repo).trimmingCharacters(in: .whitespacesAndNewlines)
  try source.assertMatches(expected)
}

@Test
func testYAMLtvOSUsesDynamicDestinationSelection() {
  let generator = Generator(
    name: "Test Generator", version: "1.2.3 (456)", link: "https://test.com")
  let repo = Repo(name: "testRepo", owner: "testOwner", platforms: [.tvOS], compilers: [.swift510])

  let source = generator.workflow(for: repo).trimmingCharacters(in: .whitespacesAndNewlines)

  #expect(source.contains("xcodebuild -workspace \"$WORKSPACE\" -scheme \"$SCHEME\" -showdestinations > logs/destinations-tvOS.log"))
  #expect(source.contains("- name: Prepare Destination Picker"))
  #expect(source.contains("pick_destination_if_available() {"))
  #expect(source.contains("pick_destination() {"))
  #expect(source.contains("boot_destination() {"))
  #expect(source.contains("source \"destination-picker.sh\""))
  #expect(source.contains("if pick_destination_if_available \"tvOS\" \"tvOS Simulator\" \"Apple TV\""))
  #expect(source.contains("xcodebuild -downloadPlatform tvOS > logs/download-tvOS.log"))
  #expect(source.contains("pick_destination \"tvOS\" \"tvOS Simulator\" \"Apple TV\" \"No available non-beta Apple TV simulator destination found.\""))
  #expect(
    source.contains("echo \"Selected tvOS simulator: ${DESTINATION_NAME:-unknown} (OS ${DESTINATION_OS:-unknown}, id=${DESTINATION_ID:-unknown}).\""))
  #expect(source.contains("boot_destination \"tvOS\" \"tvOS\""))
  #expect(
    source.contains("echo \"Testing workspace $WORKSPACE scheme $SCHEME on ${DESTINATION_NAME:-unknown} (tvOS ${DESTINATION_OS:-unknown}, id=${DESTINATION_ID:-unknown}).\""))
  #expect(
    source.contains(
      "xcodebuild test -workspace \"$WORKSPACE\" -scheme \"$SCHEME\" -destination \"platform=tvOS Simulator,OS=$DESTINATION_OS,name=$DESTINATION_NAME\" -configuration Release CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-test-release.log | xcbeautify --quiet --disable-logging --renderer github-actions"
    ))
}

@Test
func testYAMLLinuxSkipsSetupSwiftSignatureVerification() {
  let generator = Generator(
    name: "Test Generator", version: "1.2.3 (456)", link: "https://test.com")
  let repo = Repo(name: "testRepo", owner: "testOwner", platforms: [.linux], compilers: [.swift510])

  let source = generator.workflow(for: repo).trimmingCharacters(in: .whitespacesAndNewlines)

  #expect(source.contains("uses: swift-actions/setup-swift@v3"))
  #expect(source.contains("swift-version: \"5.10\""))
  #expect(source.contains("skip-verify-signature: true"))
}

@Test
func testYAMLwatchOSUsesDynamicDestinationSelection() {
  let generator = Generator(
    name: "Test Generator", version: "1.2.3 (456)", link: "https://test.com")
  let repo = Repo(name: "testRepo", owner: "testOwner", platforms: [.watchOS], compilers: [.swift510])

  let source = generator.workflow(for: repo).trimmingCharacters(in: .whitespacesAndNewlines)

  #expect(source.contains("xcodebuild -workspace \"$WORKSPACE\" -scheme \"$SCHEME\" -showdestinations > logs/destinations-watchOS.log"))
  #expect(source.contains("if pick_destination_if_available \"watchOS\" \"watchOS Simulator\" \"Apple Watch\""))
  #expect(source.contains("xcodebuild -downloadPlatform watchOS > logs/download-watchOS.log"))
  #expect(source.contains("pick_destination \"watchOS\" \"watchOS Simulator\" \"Apple Watch\" \"No available non-beta Apple Watch simulator destination found.\""))
  #expect(
    source.contains("echo \"Selected watchOS simulator: ${DESTINATION_NAME:-unknown} (OS ${DESTINATION_OS:-unknown}, id=${DESTINATION_ID:-unknown}).\""))
  #expect(source.contains("boot_destination \"watchOS\" \"watchOS\""))
  #expect(
    source.contains("echo \"Building workspace $WORKSPACE scheme $SCHEME on ${DESTINATION_NAME:-unknown} (watchOS ${DESTINATION_OS:-unknown}, id=${DESTINATION_ID:-unknown}).\""))
  #expect(
    source.contains("xcodebuild clean build -workspace \"$WORKSPACE\" -scheme \"$SCHEME\" -destination \"platform=watchOS Simulator,OS=$DESTINATION_OS,name=$DESTINATION_NAME\" -configuration Release CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-watchOS-build-release.log | xcbeautify --quiet --disable-logging --renderer github-actions"))
}

extension String {
  /// Removes leading and trailing whitespace from each line in a string,
  /// and removes empty lines.
  var removingIndentation: String {
    let lines = self.components(separatedBy: .newlines)
    let trimmed =
      lines
      .map { $0.trimmingCharacters(in: .whitespaces) }
      .filter { $0.isEmpty == false }

    return trimmed.joined(separator: "\n")
  }
}
