import ChaosTesting
import Foundation
import Matchable
import Testing

@testable import ActionBuilderCore

@Test
func testParsingPackageOldPlatform() async throws {
  // test extracting Swift version from a package which has an older tools version
  // than we currently support.
  let examplePackage = Bundle.module.url(forResource: "Example-old", withExtension: "package")!
  let repo = try await Repo(forPackage: examplePackage)
  #expect(repo.enabledCompilers.map { $0.id } == [.earliestRelease, .latestRelease])
}

@Test
func testParsingPackageMacPlatform() async throws {
  // test extracting the Swift version and platforms from a package with macOS support
  let examplePackage = Bundle.module.url(forResource: "Example-mac", withExtension: "package")!
  let repo = try await Repo(forPackage: examplePackage)
  #expect(repo.enabledCompilers.map { $0.id } == [.swift57, .latestRelease])
  #expect(repo.enabledPlatforms.map { $0.id } == [.macOS])
}

@Test
func testParsingPackageMultiPlatform() async throws {
  // test extracting the Swift version and platforms from a package with multiple platform support
  let examplePackage = Bundle.module.url(forResource: "Example-multi", withExtension: "package")!
  let repo = try await Repo(forPackage: examplePackage)
  #expect(repo.compilers == [.swift60, .swiftLatest])
  #expect(repo.platforms == [.iOS, .linux, .macOS, .tvOS])
}

@Test
func testParsingPackageConfigFile() async throws {
  let examplePackage = Bundle.module.url(forResource: "Example-config", withExtension: "package")!
  let repo = try await Repo(forPackage: examplePackage)
  #expect(repo.name == "ConfigTestPackage")
  #expect(repo.owner == "ConfigTestOwner")
  #expect(repo.compilers == [.swift60, .swiftNightly])
  #expect(repo.platforms == [.macOS, .linux])
  #expect(repo.testMode == .test)
  #expect(!repo.header)
  #expect(!repo.uploadLogs)
  #expect(!repo.postSlackNotification)
  #expect(!repo.firstlast)
}

@Test
func testYAMLmacOSSwift57() async throws {
  let expected = """
    # --------------------------------------------------------------------------------
    # This workflow was automatically generated by Test Generator 1.2.3 (456).
    # (see https://test.com for more details)
    # --------------------------------------------------------------------------------
    name: Tests
    on: [push, pull_request]
    jobs:
        macOS-swift57:
            name: macOS (Swift 5.7)
            runs-on: macos-13
            steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install xcbeautify
              run: brew install xcbeautify
            - name: Make Logs Directory
              run: mkdir logs
            - name: Select Swift
              uses: swift-actions/setup-swift@v2
              with:
                swift-version: "5.7"
            - name: Swift Version
              run: swift --version
            - name: Build (release)
              run: swift build --configuration release
            - name: Test (release)
              run: |
                set -o pipefail
                swift test --configuration release | xcbeautify --quiet --disable-logging --renderer github-actions

    """

  let generator = Generator(
    name: "Test Generator", version: "1.2.3 (456)", link: "https://test.com")
  let repo = Repo(name: "testRepo", owner: "testOwner", platforms: [.macOS], compilers: [.swift57])

  let source = generator.workflow(for: repo)
  try source.assertMatches(expected)
}

@Test
func testYAMLiOSSwift57() throws {
  let expected = """
    # --------------------------------------------------------------------------------
    # This workflow was automatically generated by Test Generator 1.2.3 (456).
    # (see https://test.com for more details)
    # --------------------------------------------------------------------------------
    name: Tests
    on: [push, pull_request]
    jobs:
        xcode-swift57:
            name: iOS (Swift 5.7, Xcode matching Swift 5.7)
            runs-on: macos-13
            steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install xcbeautify
              run: brew install xcbeautify
            - name: Make Logs Directory
              run: mkdir logs
            - name: Resolve Xcode Version
              id: resolve-xcode
              run: |
                REQUESTED_SWIFT="5.7"
                ls -d /Applications/Xcode* > logs/xcode-versions.log
                FOUND_XCODE=""
                while read -r APP
                do
                  DEV_DIR="$APP/Contents/Developer"
                  SWIFT_VERSION=$(DEVELOPER_DIR="$DEV_DIR" xcrun swift --version 2>/dev/null | head -n 1 | sed -E 's/.*version ([0-9]+\\.[0-9]+).*/\\1/')
                  XCODE_VERSION=$(DEVELOPER_DIR="$DEV_DIR" xcodebuild -version 2>/dev/null | awk '/^Xcode / {print $2; exit}')
                  if [[ "$SWIFT_VERSION" == "$REQUESTED_SWIFT" ]]
                  then
                    FOUND_XCODE="$XCODE_VERSION"
                    break
                  fi
                done < <(ls -d /Applications/Xcode*.app | sort -Vr)

                if [[ "$FOUND_XCODE" == "" ]]
                then
                  echo "No installed Xcode matched Swift $REQUESTED_SWIFT."
                  echo "Detected toolchains:"
                  while read -r APP
                  do
                    DEV_DIR="$APP/Contents/Developer"
                    XCODE_VERSION=$(DEVELOPER_DIR="$DEV_DIR" xcodebuild -version 2>/dev/null | awk '/^Xcode / {print $2; exit}')
                    SWIFT_VERSION=$(DEVELOPER_DIR="$DEV_DIR" xcrun swift --version 2>/dev/null | head -n 1 | sed -E 's/.*version ([0-9]+\\.[0-9]+).*/\\1/')
                    echo "  Xcode $XCODE_VERSION -> Swift $SWIFT_VERSION"
                  done < <(ls -d /Applications/Xcode*.app | sort -Vr)
                  exit 1
                fi

                echo "version=$FOUND_XCODE" >> "$GITHUB_OUTPUT"
            - name: Select Xcode Version
              uses: maxim-lobanov/setup-xcode@v1
              with:
                xcode-version: ${{ steps.resolve-xcode.outputs.version }}
            - name: Xcode Version
              run: |
                xcodebuild -version
                swift --version
            - name: Detect Workspace & Scheme (iOS)
              run: |
                WORKSPACE="testRepo.xcworkspace"
                if [[ ! -e "$WORKSPACE" ]]
                then
                  WORKSPACE="."
                  GOTPACKAGE=$(xcodebuild -workspace . -list | (grep testRepo-Package || true))
                  if [[ $GOTPACKAGE != "" ]]
                  then
                    SCHEME="testRepo-Package"
                  else
                    SCHEME="testRepo"
                  fi
                else
                  SCHEME="testRepo-iOS"
                fi
                echo "export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
            - name: Test (iOS Release)
              run: |
                set -o pipefail
                source "setup.sh"
                xcodebuild -downloadPlatform iOS > logs/download-iOS.log
                xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -showdestinations > logs/destinations-iOS.log
                DESTINATION=$(cat logs/destinations-iOS.log | grep "platform:iOS Simulator" | grep "name:iPhone" | head -n 1 | awk -F" }" '{print$1}' | awk -F"name:" '{print$2}')
                echo "Testing workspace $WORKSPACE scheme $SCHEME on $DESTINATION."
                xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=$DESTINATION" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcbeautify --quiet --disable-logging --renderer github-actions
            - name: Upload Logs
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: xcode-swift57-logs
                path: logs

    """

  let generator = Generator(
    name: "Test Generator", version: "1.2.3 (456)", link: "https://test.com")
  let repo = Repo(name: "testRepo", owner: "testOwner", platforms: [.iOS], compilers: [.swift57])

  let source = generator.workflow(for: repo).trimmingCharacters(in: .whitespacesAndNewlines)
  try source.assertMatches(expected)
}

extension String {
  /// Removes leading and trailing whitespace from each line in a string,
  /// and removes empty lines.
  var removingIndentation: String {
    let lines = self.components(separatedBy: .newlines)
    let trimmed =
      lines
      .map { $0.trimmingCharacters(in: .whitespaces) }
      .filter { $0.isEmpty == false }

    return trimmed.joined(separator: "\n")
  }
}
