// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
//  Created by Sam Deane on 23/07/2026.
//  Copyright © 2026 Elegant Chaos Limited. All rights reserved.
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

import Testing

@testable import ActionBuilderCore

/// Tests caller and reusable workflow generation.
struct GeneratorTests {
  /// Generator metadata used by all workflow tests.
  private let generator = Generator(
    name: "Test Generator",
    version: "1.2.3 (456)",
    link: "https://test.com"
  )

  /// Workflow generation always returns the caller followed by both helpers.
  @Test
  func workflowFilesHaveStablePaths() {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.iOS, .linux, .macOS],
      compilers: [.swift510]
    )

    #expect(
      generator.workflowFiles(for: repo).map(\.relativePath) == [
        ".github/workflows/Tests.yml",
        ".github/workflows/ActionBuilderSwiftJob.yml",
        ".github/workflows/ActionBuilderXcodeJob.yml",
      ])
  }

  /// Workflow names are sanitized before being used as file paths.
  @Test
  func workflowFilenameCannotCreateSubdirectories() {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      workflow: "CI/Nightly",
      platforms: [.macOS],
      compilers: [.swift510]
    )

    #expect(
      generator.workflowFiles(for: repo).first?.relativePath
        == ".github/workflows/CI-Nightly.yml")
    #expect(generator.workflow(for: repo).contains("name: \"CI/Nightly\""))
  }

  /// Dynamic YAML strings escape control characters.
  @Test
  func workflowNameEscapesControlCharacters() {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      workflow: "CI\nNightly",
      platforms: [.macOS],
      compilers: [.swift510]
    )

    #expect(generator.workflow(for: repo).contains("name: \"CI\\nNightly\""))
  }

  /// A simple caller has a compact, deterministic representation.
  @Test
  func macOSCallerMatchesExpectedOutput() {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.macOS],
      compilers: [.swift510]
    )

    let expected =
      """
      # --------------------------------------------------------------------------------
      # This workflow was automatically generated by Test Generator 1.2.3 (456).
      # (see https://test.com for more details)
      #
      # Job implementations:
      #   .github/workflows/ActionBuilderSwiftJob.yml
      #   .github/workflows/ActionBuilderXcodeJob.yml
      # --------------------------------------------------------------------------------

      name: "Tests"

      on: [push, pull_request]

      jobs:
        macOS-swift510:
          name: "macOS (Swift 5.10)"
          uses: ./.github/workflows/ActionBuilderSwiftJob.yml
          with:
            platform: "macOS"
            runner: "macos-14"
            swift-version: "5.10"
            compiler-id: "swift510"
            setup-mode: "release"
            xcode-version: "15.4"
            toolchain-branch: ""
            operation: "test"
            separate-test-methods: false
            upload-logs: true
            post-slack: false
            notification-job-name: "macOS (Swift 5.10)"
      """

    #expect(generator.workflow(for: repo) == expected + "\n")
  }

  /// Mixed platforms delegate to the appropriate reusable workflow.
  @Test
  func mixedCallerUsesSwiftAndXcodeHelpers() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.iOS, .linux, .macOS],
      compilers: [.swift510]
    )
    let workflow = try workflow(named: "Tests.yml", for: repo)

    #expect(workflow.contains("uses: ./.github/workflows/ActionBuilderSwiftJob.yml"))
    #expect(workflow.contains("uses: ./.github/workflows/ActionBuilderXcodeJob.yml"))
    #expect(workflow.contains("platform: \"linux\""))
    #expect(workflow.contains("platform: \"macOS\""))
    #expect(workflow.contains("platform: \"iOS\""))
    #expect(workflow.contains("preferred-xcode-version: \"15.4\""))
    #expect(workflow.contains("steps:") == false)
  }

  /// Linux and macOS share the Swift helper while retaining platform-specific setup.
  @Test
  func swiftHelperSupportsLinuxAndMacOS() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.linux, .macOS],
      compilers: [.swift510]
    )
    let workflow = try workflow(named: "ActionBuilderSwiftJob.yml", for: repo)

    #expect(workflow.contains("workflow_call:"))
    #expect(workflow.contains("runs-on: ${{ inputs.runner }}"))
    #expect(
      workflow.contains(
        "if: ${{ inputs.setup-mode == 'release' && inputs.platform == 'linux' }}"))
    #expect(workflow.contains("skip-verify-signature: true"))
    #expect(workflow.contains("if: ${{ inputs.platform == 'macOS' }}"))
    #expect(workflow.contains("swift build --configuration release --quiet"))
    #expect(
      workflow.contains(
        """
        - name: Test (release XCTest)
                  if: ${{ inputs.operation == 'test' && inputs.separate-test-methods }}
        """))
    #expect(workflow.contains("swift test --disable-swift-testing --configuration release"))
    #expect(workflow.contains("swift test --disable-xctest --configuration release"))
    #expect(workflow.contains("name: ${{ inputs.platform }}-${{ inputs.compiler-id }}-logs"))
  }

  /// Swift 5.10 uses one combined test command rather than separate test runners.
  @Test
  func callerDisablesSeparateTestsForSwift510() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.linux],
      compilers: [.swift510]
    )

    #expect(try workflow(named: "Tests.yml", for: repo).contains("separate-test-methods: false"))
  }

  /// Later Swift versions enable separate XCTest and Swift Testing commands.
  @Test
  func callerEnablesSeparateTestsForModernSwift() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.linux],
      compilers: [.swift62]
    )

    #expect(try workflow(named: "Tests.yml", for: repo).contains("separate-test-methods: true"))
  }

  /// The Xcode helper maps each supported platform to its simulator family.
  @Test
  func xcodeHelperSupportsSimulatorPlatforms() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.iOS, .tvOS, .watchOS, .visionOS],
      compilers: [.swift510]
    )
    let workflow = try workflow(named: "ActionBuilderXcodeJob.yml", for: repo)

    #expect(workflow.contains("case \"$PLATFORM\" in"))
    #expect(workflow.contains("SIMULATOR_PLATFORM=\"iOS Simulator\""))
    #expect(workflow.contains("SIMULATOR_PLATFORM=\"tvOS Simulator\""))
    #expect(workflow.contains("SIMULATOR_PLATFORM=\"watchOS Simulator\""))
    #expect(workflow.contains("SIMULATOR_PLATFORM=\"visionOS Simulator\""))
    #expect(workflow.contains("xcodebuild -downloadPlatform \"$PLATFORM\""))
    #expect(workflow.contains("inputs.operation == 'test'"))
    #expect(workflow.contains("inputs.operation == 'build'"))
  }

  /// watchOS callers build while testable Xcode platforms run tests.
  @Test
  func callerSelectsSupportedXcodeOperation() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.iOS, .watchOS],
      compilers: [.swift510]
    )
    let workflow = try workflow(named: "Tests.yml", for: repo)

    #expect(
      workflow.contains(
        """
        platform: "iOS"
              runner: "macos-14"
              swift-version: "5.10"
              compiler-id: "swift510"
              preferred-xcode-version: "15.4"
              setup-mode: "xcode-release"
              xcode-version: "15.4"
              toolchain-branch: ""
              operation: "test"
        """))
    #expect(
      workflow.contains(
        """
        platform: "watchOS"
              runner: "macos-14"
              swift-version: "5.10"
              compiler-id: "swift510"
              preferred-xcode-version: "15.4"
              setup-mode: "xcode-release"
              xcode-version: "15.4"
              toolchain-branch: ""
              operation: "build"
        """))
  }

  /// Every selected build configuration gets Swift and Xcode steps.
  @Test
  func helpersContainEveryConfiguration() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.iOS, .macOS],
      compilers: [.swift62],
      configurations: [.debug, .release]
    )
    let swiftWorkflow = try workflow(named: "ActionBuilderSwiftJob.yml", for: repo)
    let xcodeWorkflow = try workflow(named: "ActionBuilderXcodeJob.yml", for: repo)

    #expect(swiftWorkflow.contains("Build (debug)"))
    #expect(swiftWorkflow.contains("Build (release)"))
    #expect(xcodeWorkflow.contains("Test (${{ inputs.platform }} Debug)"))
    #expect(xcodeWorkflow.contains("Test (${{ inputs.platform }} Release)"))
  }

  /// Slack-enabled callers inherit secrets and helpers declare the webhook.
  @Test
  func slackNotificationsInheritWebhookSecret() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.linux],
      compilers: [.swift62],
      postSlackNotification: true
    )
    let caller = try workflow(named: "Tests.yml", for: repo)
    let helper = try workflow(named: "ActionBuilderSwiftJob.yml", for: repo)

    #expect(caller.contains("post-slack: true"))
    #expect(caller.contains("secrets: inherit"))
    #expect(helper.contains("SLACK_WEBHOOK:"))
    #expect(helper.contains("url: ${{ secrets.SLACK_WEBHOOK }}"))
  }

  /// Nightly compiler jobs select development or Xcode toolchain setup by platform.
  @Test
  func nightlyCallerSelectsPlatformSpecificSetup() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.linux, .macOS],
      compilers: [.swiftNightly]
    )
    let caller = try workflow(named: "Tests.yml", for: repo)

    #expect(caller.contains("setup-mode: \"development\""))
    #expect(caller.contains("setup-mode: \"xcode-toolchain\""))
    #expect(caller.contains("toolchain-branch: \"development\""))
  }

  /// Returns generated contents for a workflow filename.
  private func workflow(named name: String, for repo: Repo) throws -> String {
    let file = try #require(
      generator.workflowFiles(for: repo).first {
        $0.relativePath == ".github/workflows/\(name)"
      })
    return file.contents
  }
}
