// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
//  Created by Sam Deane on 23/07/2026.
//  Copyright © 2026 Elegant Chaos Limited. All rights reserved.
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

import Testing

@testable import ActionBuilderCore

/// Tests caller and reusable workflow generation.
struct GeneratorTests {
  /// Generator metadata used by all workflow tests.
  private let generator = Generator(
    name: "Test Generator",
    version: "1.2.3 (456)",
    link: "https://test.com"
  )

  /// Workflow generation always returns the caller followed by both helpers.
  @Test
  func workflowFilesHaveStablePaths() {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.iOS, .linux, .macOS],
      compilers: [.swift510]
    )

    #expect(
      generator.workflowFiles(for: repo).map(\.relativePath) == [
        ".github/workflows/Tests.yml",
        ".github/workflows/ActionBuilderSwiftJob.yml",
        ".github/workflows/ActionBuilderXcodeJob.yml",
      ])
  }

  /// Workflow names are sanitized before being used as file paths.
  @Test
  func workflowFilenameCannotCreateSubdirectories() {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      workflow: "CI/Nightly",
      platforms: [.macOS],
      compilers: [.swift510]
    )

    #expect(
      generator.workflowFiles(for: repo).first?.relativePath
        == ".github/workflows/CI-Nightly.yml")
    #expect(generator.workflow(for: repo).contains("name: \"CI/Nightly\""))
  }

  /// Dynamic YAML strings escape control characters.
  @Test
  func workflowNameEscapesControlCharacters() {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      workflow: "CI\nNightly",
      platforms: [.macOS],
      compilers: [.swift510]
    )

    #expect(generator.workflow(for: repo).contains("name: \"CI\\nNightly\""))
  }

  /// A simple caller has a compact, deterministic representation.
  @Test
  func macOSCallerMatchesExpectedOutput() {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.macOS],
      compilers: [.swift510]
    )

    let expected =
      """
      # --------------------------------------------------------------------------------
      # This workflow was automatically generated by Test Generator 1.2.3 (456).
      # (see https://test.com for more details)
      #
      # Job implementations:
      #   .github/workflows/ActionBuilderSwiftJob.yml
      #   .github/workflows/ActionBuilderXcodeJob.yml
      # --------------------------------------------------------------------------------

      name: "Tests"

      on: [push, pull_request]

      jobs:
        macOS-swift510:
          name: "macOS (Swift 5.10)"
          uses: ./.github/workflows/ActionBuilderSwiftJob.yml
          with:
            platform: "macOS"
            runner: "macos-14"
            swift-version: "5.10"
            compiler-id: "swift510"
            setup-mode: "release"
            operation: "test"
      """

    #expect(generator.workflow(for: repo) == expected + "\n")
  }

  /// Mixed platforms delegate to the appropriate reusable workflow.
  @Test
  func mixedCallerUsesSwiftAndXcodeHelpers() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.iOS, .linux, .macOS],
      compilers: [.swift510]
    )
    let workflow = try workflow(named: "Tests.yml", for: repo)

    #expect(workflow.contains("uses: ./.github/workflows/ActionBuilderSwiftJob.yml"))
    #expect(workflow.contains("uses: ./.github/workflows/ActionBuilderXcodeJob.yml"))
    #expect(workflow.contains("platform: \"linux\""))
    #expect(workflow.contains("platform: \"macOS\""))
    #expect(workflow.contains("platform: \"iOS\""))
    #expect(workflow.contains("preferred-xcode-version: \"15.4\""))
    #expect(workflow.contains("steps:") == false)
  }

  /// Each reusable workflow declares every required input supplied by its callers.
  @Test
  func reusableWorkflowInputContractsMatchCallers() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.iOS, .linux],
      compilers: [.swift62]
    )
    let swiftWorkflow = try workflow(named: "ActionBuilderSwiftJob.yml", for: repo)
    let xcodeWorkflow = try workflow(named: "ActionBuilderXcodeJob.yml", for: repo)
    let operationNameInput =
      """
            operation-name:
              required: true
              type: string
      """

    #expect(swiftWorkflow.contains(operationNameInput) == false)
    #expect(xcodeWorkflow.contains(operationNameInput))
  }

  /// Linux and macOS share the Swift helper while retaining platform-specific setup.
  @Test
  func swiftHelperSupportsLinuxAndMacOS() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.linux, .macOS],
      compilers: [.swift62],
      testFrameworks: [.xctest, .swiftTesting]
    )
    let workflow = try workflow(named: "ActionBuilderSwiftJob.yml", for: repo)

    #expect(workflow.contains("workflow_call:"))
    #expect(workflow.contains("runs-on: ${{ inputs.runner }}"))
    #expect(workflow.contains("if: ${{ inputs.setup-mode == 'release' }}"))
    #expect(workflow.contains("skip-verify-signature: ${{ inputs.platform == 'linux' }}"))
    #expect(workflow.contains("Select Swift on Linux") == false)
    #expect(workflow.contains("INSTALL_XCBEAUTIFY: ${{ inputs.platform == 'macOS' }}"))
    #expect(workflow.contains("- name: Install xcbeautify") == false)
    #expect(
      workflow.contains(
        """
                - name: Select Swift
                  if: ${{ inputs.setup-mode == 'release' }}
        """))
    #expect(workflow.contains("swift build --configuration release --quiet"))
    #expect(
      workflow.contains(
        """
        - name: Test (release XCTest)
                  if: ${{ inputs.operation == 'test' }}
        """))
    #expect(workflow.contains("swift test --disable-swift-testing --configuration release"))
    #expect(workflow.contains("swift test --disable-xctest --configuration release"))
    #expect(workflow.contains("name: ${{ inputs.platform }}-${{ inputs.compiler-id }}-logs"))
  }

  /// A Swift Testing-only package emits only its relevant modern test command.
  @Test
  func swiftTestingPackageEmitsOnlySwiftTestingStep() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.linux],
      compilers: [.swift62],
      testFrameworks: [.swiftTesting]
    )
    let helper = try workflow(named: "ActionBuilderSwiftJob.yml", for: repo)

    #expect(helper.contains("- name: Test (release Swift Testing)"))
    #expect(helper.contains("- name: Test (release XCTest)") == false)
    #expect(helper.contains("- name: Test (release)\n") == false)
    #expect(helper.contains("jobs:\n  run:"))
    #expect(helper.contains("Select Swift Development Snapshot") == false)
    #expect(helper.contains("Select Swift Snapshot") == false)
    #expect(helper.contains("Install Swift Snapshot Toolchain") == false)
    #expect(helper.contains("Slack Notification") == false)
  }

  /// An XCTest-only package emits only its relevant modern test command.
  @Test
  func xctestPackageEmitsOnlyXCTestStep() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.linux],
      compilers: [.swift62],
      testFrameworks: [.xctest]
    )
    let helper = try workflow(named: "ActionBuilderSwiftJob.yml", for: repo)

    #expect(helper.contains("- name: Test (release XCTest)"))
    #expect(helper.contains("- name: Test (release Swift Testing)") == false)
    #expect(helper.contains("- name: Test (release)\n") == false)
  }

  /// Packages containing both frameworks run each framework separately on modern Swift.
  @Test
  func mixedTestPackageEmitsBothModernTestSteps() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.linux],
      compilers: [.swift62],
      testFrameworks: [.xctest, .swiftTesting]
    )
    let helper = try workflow(named: "ActionBuilderSwiftJob.yml", for: repo)

    #expect(helper.contains("- name: Test (release XCTest)"))
    #expect(helper.contains("- name: Test (release Swift Testing)"))
    #expect(helper.contains("- name: Test (release)\n") == false)
  }

  /// Swift 5.10 uses one combined test command because it lacks framework filters.
  @Test
  func olderCompilerEmitsCombinedTestStep() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.linux],
      compilers: [.swift510],
      testFrameworks: [.swiftTesting]
    )
    let helper = try workflow(named: "ActionBuilderSwiftJob.yml", for: repo)

    #expect(helper.contains("- name: Test (release)\n"))
    #expect(helper.contains("- name: Test (release XCTest)") == false)
    #expect(helper.contains("- name: Test (release Swift Testing)") == false)
  }

  /// Unrecognized test infrastructure falls back to the compatible combined command.
  @Test
  func unknownFrameworkPackageEmitsCombinedTestStep() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.linux],
      compilers: [.swift62],
      testFrameworks: []
    )
    let helper = try workflow(named: "ActionBuilderSwiftJob.yml", for: repo)

    #expect(helper.contains("- name: Test (release)\n"))
    #expect(helper.contains("--disable-swift-testing") == false)
    #expect(helper.contains("--disable-xctest") == false)
  }

  /// Mixed compiler capabilities select filtered or combined commands per caller.
  @Test
  func mixedCompilerCapabilitiesEmitCompatibleTestSteps() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.linux],
      compilers: [.swift510, .swift62],
      testFrameworks: [.swiftTesting]
    )
    let caller = try workflow(named: "Tests.yml", for: repo)
    let helper = try workflow(named: "ActionBuilderSwiftJob.yml", for: repo)

    #expect(caller.contains("separate-test-methods: false"))
    #expect(caller.contains("separate-test-methods: true"))
    #expect(helper.contains("inputs.operation == 'test' && inputs.separate-test-methods"))
    #expect(helper.contains("inputs.operation == 'test' && !inputs.separate-test-methods"))
  }

  /// The Xcode helper maps each supported platform to its simulator family.
  @Test
  func xcodeHelperSupportsSimulatorPlatforms() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.iOS, .tvOS, .watchOS, .visionOS],
      compilers: [.swift510]
    )
    let workflow = try workflow(named: "ActionBuilderXcodeJob.yml", for: repo)

    #expect(workflow.contains("case \"$PLATFORM\" in"))
    #expect(workflow.contains("SIMULATOR_PLATFORM=\"iOS Simulator\""))
    #expect(workflow.contains("SIMULATOR_PLATFORM=\"tvOS Simulator\""))
    #expect(workflow.contains("SIMULATOR_PLATFORM=\"watchOS Simulator\""))
    #expect(workflow.contains("SIMULATOR_PLATFORM=\"visionOS Simulator\""))
    #expect(workflow.contains("xcodebuild -downloadPlatform \"$PLATFORM\""))
    #expect(workflow.contains("- name: ${{ inputs.operation-name }}"))
    #expect(
      workflow.contains(
        """
                - name: ${{ inputs.operation-name }} (${{ inputs.platform }} Release)
                  if: ${{ steps.select-destination.outputs.available == 'true' }}
        """))
    #expect(workflow.contains("if [[ \"$OPERATION\" == \"test\" ]]"))
    #expect(workflow.contains("ACTION=(test)"))
    #expect(workflow.contains("ACTION=(clean build)"))
  }

  /// watchOS callers build while testable Xcode platforms run tests.
  @Test
  func callerSelectsSupportedXcodeOperation() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.iOS, .watchOS],
      compilers: [.swift510]
    )
    let workflow = try workflow(named: "Tests.yml", for: repo)

    #expect(
      workflow.contains(
        """
        platform: "iOS"
              runner: "macos-14"
              swift-version: "5.10"
              compiler-id: "swift510"
              preferred-xcode-version: "15.4"
              setup-mode: "xcode-release"
              operation: "test"
              operation-name: "Test"
        """))
    #expect(
      workflow.contains(
        """
        platform: "watchOS"
              runner: "macos-14"
              swift-version: "5.10"
              compiler-id: "swift510"
              preferred-xcode-version: "15.4"
              setup-mode: "xcode-release"
              operation: "build"
              operation-name: "Build"
        """))
  }

  /// Every selected build configuration gets Swift and Xcode steps.
  @Test
  func helpersContainEveryConfiguration() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.iOS, .macOS],
      compilers: [.swift62],
      configurations: [.debug, .release]
    )
    let swiftWorkflow = try workflow(named: "ActionBuilderSwiftJob.yml", for: repo)
    let xcodeWorkflow = try workflow(named: "ActionBuilderXcodeJob.yml", for: repo)

    #expect(swiftWorkflow.contains("Build (debug)"))
    #expect(swiftWorkflow.contains("Build (release)"))
    #expect(xcodeWorkflow.contains("${{ inputs.operation-name }} (${{ inputs.platform }} Debug)"))
    #expect(xcodeWorkflow.contains("${{ inputs.operation-name }} (${{ inputs.platform }} Release)"))
  }

  /// Slack-enabled callers inherit secrets and helpers declare the webhook.
  @Test
  func slackNotificationsInheritWebhookSecret() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.linux],
      compilers: [.swift62],
      postSlackNotification: true
    )
    let caller = try workflow(named: "Tests.yml", for: repo)
    let helper = try workflow(named: "ActionBuilderSwiftJob.yml", for: repo)

    #expect(caller.contains("secrets: inherit"))
    #expect(caller.contains("notification-job-name: \"Linux (Swift 6.2)\""))
    #expect(helper.contains("SLACK_WEBHOOK:"))
    #expect(helper.contains("url: ${{ secrets.SLACK_WEBHOOK }}"))
  }

  /// Nightly compiler jobs select development or Xcode toolchain setup by platform.
  @Test
  func nightlyCallerSelectsPlatformSpecificSetup() throws {
    let repo = Repo(
      name: "testRepo",
      owner: "testOwner",
      platforms: [.linux, .macOS],
      compilers: [.swiftNightly]
    )
    let caller = try workflow(named: "Tests.yml", for: repo)

    #expect(caller.contains("setup-mode: \"development\""))
    #expect(caller.contains("setup-mode: \"xcode-toolchain\""))
    #expect(caller.contains("toolchain-branch: \"development\""))
  }

  /// Returns generated contents for a workflow filename.
  private func workflow(named name: String, for repo: Repo) throws -> String {
    let file = try #require(
      generator.workflowFiles(for: repo).first {
        $0.relativePath == ".github/workflows/\(name)"
      })
    return file.contents
  }
}
