import XCTest
@testable import ActionBuilderCore

struct MockRepo: RepoDetails {
    let owner = "testOwner"
    let name = "testRepo"
    let workflow = "Tests"
    var settings: ActionBuilderCore.WorkflowSettings

    init(_ options: [String]) {
        settings = WorkflowSettings(options: options)
    }
    
}

final class ActionBuilderCoreTests: XCTestCase {
    func testGenerator() {
        let expected = """
            # --------------------------------------------------------------------------------
            # This workflow was automatically generated by Test Generator 1.2.3 (456).
            # (see https://test.com for more details)
            # --------------------------------------------------------------------------------

            name: Tests

            on: [push, pull_request]

            jobs:
            
            """
        
        let repo = MockRepo([])
        let generator = WorkflowGenerator(name: "Test Generator", version: "1.2.3 (456)", link: "https://test.com")
        
        let output = generator.generateWorkflow(for: repo)!
        XCTAssertEqual(output.source, expected)
    }
}
