#!/usr/bin/env bash
set -euo pipefail

SOURCE="${BASH_SOURCE[0]}"
while [ -L "$SOURCE" ]
do
    SCRIPT_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
    SOURCE="$(readlink "$SOURCE")"
    case "$SOURCE" in
        /*) ;;
        *) SOURCE="$SCRIPT_DIR/$SOURCE" ;;
    esac
done

SCRIPT_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
PACKAGE_DIR="$REPO_ROOT/Tests/EndToEndTests"
GENERATED_WORKFLOW_DIR="$PACKAGE_DIR/.github/workflows"
GENERATED_CALLER="$GENERATED_WORKFLOW_DIR/EndToEndTests.yml"
GENERATED_SWIFT_HELPER="$GENERATED_WORKFLOW_DIR/EndToEndSwiftJob.yml"
GENERATED_XCODE_HELPER="$GENERATED_WORKFLOW_DIR/EndToEndXcodeJob.yml"
ROOT_WORKFLOW_DIR="$REPO_ROOT/.github/workflows"
GATE_TEMPLATE="$SCRIPT_DIR/endtoend-current-job.yml"

cd "$REPO_ROOT"

swift build --product ActionBuilderTool
"$REPO_ROOT/.build/debug/ActionBuilderTool" "$PACKAGE_DIR"

mv "$GENERATED_WORKFLOW_DIR/ActionBuilderSwiftJob.yml" "$GENERATED_SWIFT_HELPER"
mv "$GENERATED_WORKFLOW_DIR/ActionBuilderXcodeJob.yml" "$GENERATED_XCODE_HELPER"

# The repository build number changes when refreshed files are committed, so it
# cannot participate in a stable generated-file comparison.
perl -0pi -e '
    s/(automatically generated by ActionBuilderTool [^\s]+) \([^)]+\)/$1/g;
' "$GENERATED_CALLER" "$GENERATED_SWIFT_HELPER" "$GENERATED_XCODE_HELPER"

perl -0pi -e '
    s/ActionBuilderSwiftJob\.yml/EndToEndSwiftJob.yml/g;
    s/ActionBuilderXcodeJob\.yml/EndToEndXcodeJob.yml/g;
    s/^(  [A-Za-z0-9_-]+:\n)(    name:)/$1    needs: generated-workflows-current\n$2/mg;
' "$GENERATED_CALLER"

GENERATED_JOB_COUNT=$(awk '/^  [A-Za-z0-9_-]+:$/ { count++ } END { print count + 0 }' "$GENERATED_CALLER")
DEPENDENT_JOB_COUNT=$(awk '$0 == "    needs: generated-workflows-current" { count++ } END { print count + 0 }' "$GENERATED_CALLER")
if [[ "$GENERATED_JOB_COUNT" -eq 0 || "$GENERATED_JOB_COUNT" -ne "$DEPENDENT_JOB_COUNT" ]]
then
    echo "Failed to make every generated EndToEnd job depend on the freshness gate." >&2
    exit 1
fi

perl -0pi -e '
    s/(    runs-on: \$\{\{ inputs\.runner \}\}\n)/$1    defaults:\n      run:\n        working-directory: Tests\/EndToEndTests\n/;
' "$GENERATED_SWIFT_HELPER" "$GENERATED_XCODE_HELPER"

END_TO_END_GATE_TEMPLATE="$GATE_TEMPLATE" perl -0pi -e '
    BEGIN {
        local $/;
        open my $template, "<", $ENV{END_TO_END_GATE_TEMPLATE} or die $!;
        $gate = <$template>;
        close $template;
    }
    s/^jobs:\n/"jobs:\n$gate\n"/me;
' "$GENERATED_CALLER"

mkdir -p "$ROOT_WORKFLOW_DIR"
cp "$GENERATED_CALLER" "$ROOT_WORKFLOW_DIR/EndToEndTests.yml"
cp "$GENERATED_SWIFT_HELPER" "$ROOT_WORKFLOW_DIR/EndToEndSwiftJob.yml"
cp "$GENERATED_XCODE_HELPER" "$ROOT_WORKFLOW_DIR/EndToEndXcodeJob.yml"

echo "Refreshed EndToEnd workflows in: $ROOT_WORKFLOW_DIR"
